### ISSUE TITLE
Tick rate change does not affect crop growth

### ISSUE THREAD

**Issue by xkforce** [Guichaguri/TickrateChanger#6]
Changing the tick rate of the game does not change the rate at which crops grow but it does affect other aspects of the game as expected.  i.e. mobs move faster, the day/night cycle is accordingly faster, furnaces smelt more items etc. which makes the normal crop growth rate look very out of place.

**Comment by Guichaguri** [comment]
It does affect, but not much as you would expect. Crop growth is mainly affected by random ticks, basically, each tick the game picks a number of random blocks to update, if they pick a crop, there's another random chance for it to grow.

If you want to speed random ticks, use the `/gamerule randomTickSpeed {number}` command, as it allows you to change the amount of blocks that are randomly picked each tick.

**Comment by xkforce** [comment]
Sleepingoverhaul uses this mod to accelerate the tick rate when a bed is used in order to simulate the passage of time as the player sleeps.

**Comment by xkforce** [comment]
So given that the randomtickrate issue for sleepingoverhaul has been closed as "wontfix" any idea how I could got randomtickrate to be properly coupled to sleeping so that crops and anything else subject to that gamerule are accelerated to match the amount of time the player sleeps?

**Comment by Guichaguri** [comment]
It looks like it's not working because the growth is very slow, but it does. Just tested myself and it worked as expected, here's my setup:

![https://i.imgur.com/E0yjJfb.png](https://i.imgur.com/E0yjJfb.png)

I tested a couple of times and it does grow faster. `randomTickSpeed` can be used to increase even more the speed, but that would be cheating.

**Comment by cosmicdan** [comment]
Thanks for looking into this, I'll be sure to make a note in the Sleeping Overhaul readme that it's a "limitation" of Minecraft itself and can only be adjusted with randomTickSpeed gamerule. I may add config in future to change the randomTickSpeed gamerule under timelapse sleep in future.

**Comment by Guichaguri** [comment]
Sorry, I think my response wasn't clear enough.

It **does** work as expected, the growth is affected.
It's not because you don't see a lot of progress happening quickly that it's not working. `randomTickSpeed` can be used to make it grow faster, but that would be unrealistic and also cheating.

Just try it out:
- Plant the crops, and don't forget to light them
- Leave your game open for a full night in the regular speed
- Replace the crops to new ones
- Speed up the time, at the end of the night, the result will be the almost the same.

**Comment by xkforce** [comment]
All I wanted was for crop growth to be consistent with everything else.  That's it.  So if the player sleeps for an hour, everything advances by an hour but since crop growth is a bit more complicated in that it uses random ticks for something like 80-90% of its growth, there's an inconsistency in how much crops grow compared to say furnaces smelting items or the day/night cycle.

If speeding up crop growth to match everything else is cheating, speeding up mob farms, machines and furnaces 50x normal is definitely cheating and that's what this mod does.

**Comment by cosmicdan** [comment]
No I understood you, I think. My mathematics are not fantastic but I believe this is due to the nature of pseudo RNG - it's deterministic, so increasing tick speed doesn't make the random tick speed increase linearly. Furthermore, the Minecraft server seems to skip a few hundred ticks when Timelapse ends.

I just tried to explain it simply on the "Known Issues" section of Sleeping Overhaul - that it "might not seem sped-up as expected due to the nature of randomness" or something like that.

A solution to this would be to make my mod have an option which can switch the random tick speed gamerule between two values when Timelapse is active Vs inactive. To let the user configure it how they want for their modpack. 

On 7 Dec 2018, Guilherme Chaguri <notifications@github.com> wrote:
>Sorry, I think my response wasn't clear enough.
>
>It **does** work as expected, the growth is affected.
>It's not because you don't see a lot of progress happening quickly that
>it's not working. `randomTickSpeed` can be used to make it grow faster,
>but that would be unrealistic and also cheating.
>
>Just try it out:
>- Plant the crops, and don't forget to light them
>- Leave your game open for a full night in the regular speed
>- Replace the crops to new ones
>- Speed up the time, at the end of the night, the result will be the
>almost the same.

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.
